spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/production-gitops-public
    targetRevision: HEAD

apiConnectVersion: '10.0.7.0'

# Type of environment to deploy (dev, prod)
envType: dev
namespaceOverride: cp4i
storage:
  blockStorage: ocs-storagecluster-ceph-rbd