apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4i-pn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: '{{ .Values.cp4iVersion }}/{{ .Values.appDir }}/{{ .Values.envType }}'
    repoURL: '{{ .Values.spec.source.repoURL }}/cp4i-platform-navigator.git'
    targetRevision: {{ .Values.spec.source.targetRevision }}
    kustomize:
      patches:
        - target:
            kind: PlatformNavigator
            labelSelector: "managed-by=kustomize-argocd"
          patch: |-
            - op: replace
              path: /metadata/namespace
              value: {{ .Values.namespaceOverride }}
        - target:
            kind: CommonService
            labelSelector: "managed-by=kustomize-argocd"
            patch: |-
              - op: replace
                path: /spec/storageClass
                value: {{ .Values.storage.blockStorage }}