apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mq
  namespace: {{ .Values.argocdNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: '{{ .Values.mqVersion }}/{{ .Values.envType }}'
    repoURL: '{{ .Values.spec.source.repoURL }}/ibm-mq.git'
    targetRevision: {{ .Values.spec.source.targetRevision }}
    kustomize:
      patches:
        - target:
            kind: QueueManager
            name: mq
          patch: |-
            - op: add
              path: /metadata/namespace
              value: {{ .Values.namespaceOverride }}
        - target:
            kind: QueueManager
            name: mq
          patch: |-
            - op: add
              path: spec/queueManager/storage/defaultClass
              value: {{ .Values.storage.fileStorage }}