apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  labels:
    app: argocd
spec:
  controller:
    resources:
      limits:
        cpu: 2000m
        memory: 2048Mi
      requests:
        cpu: 250m
        memory: 1024Mi
  rbac:
    defaultPolicy: ''
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  repo:
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 250m
        memory: 256Mi
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
  server:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    route:
      enabled: true
  sso:
    dex:
      openShiftOAuth: true
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
    provider: dex
  extraConfig:
    kustomize.buildOptions: --enable-helm
    resource.customizations: |
      argoproj.io/Application:
        health.lua: |
          hs = {}
          hs.status = "Progressing"
          hs.message = ""
          if obj.status ~= nil then
            if obj.status.health ~= nil then
              hs.status = obj.status.health.status
              if obj.status.health.message ~= nil then
                hs.message = obj.status.health.message
              end
            end
          end
          return hs
      operators.coreos.com/CatalogSource:
        health.lua: |
          hs = {}
          if obj.status ~= nil then
            if obj.status.connectionState ~= nil then
              if obj.status.connectionState.lastObservedState ~= nil then
                if obj.status.connectionState.lastObservedState == "READY" then
                  hs.status = "Healthy"
                  return hs
                end
              end
            end
          end
          hs.status = "Progressing"
          hs.message = "Unknown"
          return hs
      operators.coreos.com/InstallPlan:
        health.lua: |
          hs = {}
          if obj.status ~= nil then
            if obj.status.phase ~= nil then
              hs.message = obj.status.phase
              if obj.status.phase == "Complete" then
                hs.status = "Healthy"
              else
                hs.status = "Progressing"
              end
              return hs
            end
          end
          hs.status = "Progressing"
          hs.message = "Unknown"
          return hs
      operators.coreos.com/Subscription:
        health.lua: |
          hs = {}
          if obj.status ~= nil then
            if obj.status.installedCSV ~= nil then
              hs.status = "Healthy"
              hs.message = "CSV Installed"
              if obj.status.state ~= nil then
                hs.message = obj.status.state
              end
              return hs
            end
          end
          hs.status = "Progressing"
          hs.message = "Unknown"
          if obj.status.state ~= nil then
            hs.message = obj.status.state
          end
          return hs
    resource.compareoptions: |
      ignoreResourceStatusField: crd
    resource.customizations.ignoreDifferences.ServiceAccount: |
      jsonPointers:
      - /secrets
      - /imagePullSecrets
        
