apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssp-cm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.namespace }}
  project: default
  source:
    path: '{{ .Values.sspVersion }}/ibm-ssp-cm'
    repoURL: '{{ .Values.spec.source.repoURL }}/sterling-secure-proxy.git'
    targetRevision: {{ .Values.spec.source.targetRevision }}