apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-streams
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: '{{ .Values.eventStreamsVersion }}/{{ .Values.envType }}'
    repoURL: '{{ .Values.spec.source.repoURL }}/event-streams.git'
    targetRevision: {{ .Values.spec.source.targetRevision }}
    kustomize:
      patches:
        - target:
            kind: EventStreams
            name: event-streams
          patch: |-
            - op: add
              path: /metadata/namespace
              value: {{ .Values.namespaceOverride }}
        - target:
            kind: EventStreams
            name: event-streams
          patch: |-
            - op: add
              path: spec/strimziOverrides/kafka/storage/class
              value: {{ .Values.storage.blockStorage }}
        - target:
            kind: EventStreams
            name: event-streams
          patch: |-
            - op: add
              path: spec/strimziOverrides/zookeeper/storage/class
              value: {{ .Values.storage.blockStorage }}