apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-connect
  namespace: {{ .Values.argocdNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: '{{ .Values.apiConnectVersion }}/{{ .Values.envType }}'
    repoURL: '{{ .Values.spec.source.repoURL }}/api-connect.git'
    targetRevision: {{ .Values.spec.source.targetRevision }}
    kustomize:
      patches:
        - target:
            kind: APIConnectCluster
            name: medium
          patch: |-
            - op: add
              path: /metadata/namespace
              value: {{ .Values.namespaceOverride }}
        - target:
            kind: APIConnectCluster
            name: medium
          patch: |-
            - op: add
              path: spec/storageClassName
              value: {{ .Values.storage.blockStorage }}